=== hmcts/cpp-context-staging-pubhub/stagingpubhub-event/stagingpubhub-event-processor/src/yaml/json/schema/public.hearing.live-status-published.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://cpp.moj.gov.uk/hearing/json/schema/event/public.hearing.live-status-published.json",
  "type": "object",
  "properties": {
    "documentName": {
      "type": "string"
    },
    "documentDate": {
      "type": "string",
      "format": "date-time"
    },
    "version": {
      "type": "string"
    },
    "venueId": {
      "type": "string"
    },
    "venueType": {
      "type": "string"
    },
    "listType": {
      "type": "string"
    },
    "courtId": {
      "type": "string"
    },
    "courtCentreName": {
      "type": "string"
    },
    "address1": {
      "type": "string"
    },
    "postCode": {
      "type": "string"
    },
    "welshCourtCentreName": {
      "type": "string"
    },
    "welshAddress1": {
      "type": "string"
    },
    "hearingDate": {
      "type": "string",
      "format": "date"
    },
    "hearingDateWelsh": {
      "type": "string"
    },
    "courtRooms": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/courtRoom"
      }
    }
  },
  "additionalProperties": false,
  "definitions": {
    "hearing": {
      "id": "http://cpp.moj.gov.uk/hearing/json/schema/event/hearing.json",
      "type": "object",
      "properties": {
        "sequence": {
          "type": "integer"
        },
        "startTime": {
          "type": "string"
        },
        "hearingType": {
          "type": "string"
        },
        "welshHearingType": {
          "type": "string"
        },
        "caseNumber": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "welshCaseNumber": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "prosecutingAuthority": {
          "type": "string"
        },
        "defendants": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/defendant"
          }
        },
        "hearingEvents": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/hearingEvent"
          }
        }
      },
      "additionalProperties": false
    },
    "hearingEvent": {
      "id": "http://cpp.moj.gov.uk/hearing/json/schema/event/hearingEvent.json",
      "type": "object",
      "properties": {
        "hearingEvent": {
          "type": "string"
        },
        "hearingEventWelsh": {
          "type": "string"
        },
        "hearingEventTime": {
          "type": "string",
          "format": "date-time"
        }
      },
      "additionalProperties": false
    },
    "courtRoom": {
      "id": "http://cpp.moj.gov.uk/hearing/json/schema/event/courtRoom.json",
      "type": "object",
      "properties": {
        "roomId": {
          "type": "string"
        },
        "courtRoomName": {
          "type": "string"
        },
        "welshCourtRoomName": {
          "type": "string"
        },
        "sessions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/session"
          }
        }
      },
      "additionalProperties": false
    },
    "session": {
      "id": "http://cpp.moj.gov.uk/hearing/json/schema/event/session.json",
      "type": "object",
      "properties": {
        "sittings": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/sitting"
          }
        }
      },
      "additionalProperties": false
    },
    "sitting": {
      "id": "http://cpp.moj.gov.uk/hearing/json/schema/event/sitting.json",
      "type": "object",
      "properties": {
        "hearing": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/hearing"
          }
        },
        "judiciaries": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/judiciary"
          }
        }
      },
      "additionalProperties": false
    },
    "judiciary": {
      "id": "http://cpp.moj.gov.uk/hearing/json/schema/event/judiciary.json",
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "firstName": {
          "type": "string"
        },
        "lastName": {
          "type": "string"
        },
        "johKnownAs": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "defendant": {
      "id": "http://cpp.moj.gov.uk/hearing/json/schema/event/defendant.json",
      "type": "object",
      "properties": {
        "organisationName": {
          "type": "string"
        },
        "firstName": {
          "type": "string"
        },
        "lastName": {
          "type": "string"
        },
        "dateOfBirth": {
          "type": "string",
          "format": "date"
        },
        "age": {
          "type": "integer"
        },
        "nationality": {
          "type": "integer"
        },
        "arrestSummonsNumber": {
          "type": "string"
        },
        "bailStatus": {
          "type": "string"
        },
        "address": {
          "$ref": "http://justice.gov.uk/core/courts/address.json"
        },
        "gender": {
          "type": "string"
        },
        "offences": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/offence"
          }
        }
      },
      "additionalProperties": false
    },
    "offence": {
      "id": "http://cpp.moj.gov.uk/hearing/json/schema/event/offence.json",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
        },
        "maxPenalty": {
          "type": "string"
        },
        "listingNumber": {
          "type": "integer"
        },
        "offenceCode": {
          "type": "string"
        },
        "offenceTitle": {
          "type": "string"
        },
        "offenceLegislation": {
          "type": "string"
        },
        "committingCourt": {
          "type": "string"
        },
        "offenceWording": {
          "type": "string"
        },
        "reportingRestrictions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/reportingRestriction"
          }
        }
      },
      "additionalProperties": false
    },
    "reportingRestriction": {
      "id": "http://cpp.moj.gov.uk/hearing/json/schema/event/reportingRestriction.json",
      "type": "object",
      "properties": {
        "label": {
          "type": "string"
        }
      },
      "additionalProperties": false
    }
  }
}

=== hmcts/cpp-context-staging-pubhub/stagingpubhub-event/stagingpubhub-event-processor/src/test/resources/stub-data/stagingpubhub.event.publish-live-status.json
{
  "documentDate": "2022-07-14T10:00:00.000Z",
  "courtRooms": [
    {
      "roomId": "010",
      "courtRoomName": "Courtroom 01",
      "sessions": [
        {
          "sittings": [
            {
              "hearing": [
                {
                  "prosecutingAuthority": "CPS-EM",
                  "sequence": 1,
                  "hearingType": "First hearing",
                  "defendants": [
                    {
                      "firstName": "Robert",
                      "lastName": "Ormsby",
                      "organisationName": "",
                      "address": {
                        "address3": "Optional[Locality2O]",
                        "address2": "Optional[StreetDescription]",
                        "address1": "819",
                        "postcode": "LN5 5TT"
                      },
                      "offences": [
                        {
                          "offenceTitle": "Occupy reserved seat / berth without a valid ticket on the Tyne and Wear Metro",
                          "offenceWording": "Has a violent past and fear that he will commit further offences and\n                interfere with witnesse",
                          "id": "90aca8ef-fddd-40af-9be1-480e6c5a0f27"
                        }
                      ],
                      "dateOfBirth": "5 May 1951",
                      "age": 71
                    }
                  ],
                  "caseNumber": [
                    "53NP8105522"
                  ],
                  "hearingEvents": [
                    {
                      "hearingEvent":"Test",
                      "hearingEventTime":"2022-07-08T10:14:28.257Z"
                    }
                  ],
                  "startTime": "10:01"
                },
                {
                  "prosecutingAuthority": "CPS-EM",
                  "sequence": 2,
                  "hearingType": "First hearing",
                  "caseNumber": [
                    "53NP1454922"
                  ],
                  "startTime": "10:01"
                },
                {
                  "prosecutingAuthority": "CPS-EM",
                  "sequence": 3,
                  "hearingType": "First hearing",
                  "caseNumber": [
                    "53NP7998322"
                  ],
                  "startTime": "10:01"
                }
              ]
            }
          ]
        }
      ]
    }
  ],
  "address1": "176A Lavender Hill London",
  "hearingDate": "2022-07-11",
  "documentName": "Live Case Status Update",
  "courtCentreName": "Lavender Hill Magistrates' Court",
  "version": "1.0"
}
